# --- helpers -----------------------------------------------------------------

# _CORE_TERMS = {
#     # "en": "Annual report OR Integrated report OR CSR report OR ESG report OR Impact report OR CDP report",
#     "en": "Annual report",
#     "de": "Jahresbericht OR Integrierter Bericht OR CSR-Bericht OR ESG-Bericht OR Impact-Bericht OR CDP-Bericht",
#     "fr": "rapport annuel OR rapport intégré OR rapport RSE OR rapport ESG OR rapport d'impact OR rapport CDP",
#     "es": "informe anual OR informe integrado OR informe de RSE OR informe ESG OR informe de impacto OR informe CDP",
#     "ru": "годовой отчет OR интегрированный отчет OR отчет о корпоративной социальной ответственности OR ESG отчет OR отчет о воздействии OR отчет CDP",
#     "zh": "年度报告 OR 年報 OR 综合报告 OR 綜合報告 OR 整合报告 OR 整合報告 OR 企业社会责任报告 OR 企業社會責任報告 OR ESG报告 OR ESG報告 OR 影响报告 OR 影響報告 OR CDP报告 OR CDP報告",
#     "ja": "有価証券報告書 OR 年次報告書 OR アニュアルレポート OR 統合報告書 OR CSR報告書 OR サステナビリティレポート OR ESGレポート OR インパクトレポート OR CDP 回答 OR CDP レポート",
# }

_CORE_TERMS = {
    # "en": "climate action plan OR climate plan OR climate strategy OR climate change strategy OR climate change OR environment strategy OR resilient strategy OR climate ready OR clean energy OR resilient OR sustainable OR climate neutral OR net zero climate OR net zero OR carbon neutral OR CAAP OR climate vulnerability OR climate assessment OR climate action roadmap OR climate emergency plan OR climate mitigation plan OR climate change mitigation OR energy action plan OR mitigation plan OR SEAP",
    "en": '"climate action plan" OR "climate plan" OR "climate strategy" OR "climate change strategy" OR "climate change" OR "environment strategy" OR "resilient strategy" OR "climate ready" OR "clean energy" OR "resilient" OR "sustainable" OR "climate neutral" OR "net zero climate" OR "net zero" OR "carbon neutral" OR "CAAP" OR "climate vulnerability" OR "climate assessment" OR "climate action roadmap" OR "climate emergency plan" OR "climate mitigation plan" OR "climate change mitigation" OR "energy action plan" OR "mitigation plan" OR "SEAP"',
    "de": "klimaschutz OR Klimastrategie OR klimawandelstrategie OR Klimaplan",
    "fr": "protection du climat OU stratégie climatique OU stratégie de changement climatique OU plan climat",
    "es": "Plan de Acción Climática OR Plan climático OR Estrategia climática OR Estrategia de cambio climático OR Estrategia ambiental OR Estrategia resiliente OR Resiliente OR Sostenible OR Carbono neutral OR Vulnerabilidad climática OR Evaluación climática OR Hoja de ruta de acción climática OR Plan de emergencia climática OR Plan de mitigación climática OR Mitigación del cambio climático OR Plan de acción energética OR Plan de mitigación",
    "ru": "защита климата ИЛИ климатическая стратегия ИЛИ стратегия изменения климата ИЛИ климатический план",
    "zh": "气候保护 OR 气候战略 OR 气候变化战略 OR 气候计划",
    "ja": "気候保護 OR 気候戦略 OR 気候変動戦略 OR 気候計画",
}

_CORE_TERMS_LISTS = {
    "en": [
        "climate action plan",
        "climate plan",
        "climate strategy",
        "climate change strategy",
        "climate change",
        "environment strategy",
        "resilient strategy",
        "climate ready",
        "clean energy",
        "resilient",
        "sustainable",
        "climate neutral",
        "net zero climate",
        "net zero",
        "carbon neutral",
        "CAAP",
        "climate vulnerability",
        "climate assessment",
        "climate action roadmap",
        "climate emergency plan",
        "climate mitigation plan",
        "climate change mitigation",
        "energy action plan",
        "mitigation plan",
        "SEAP",
    ],
    "de": ["klimaschutz", "Klimastrategie", "klimawandelstrategie", "Klimaplan"],
    "fr": [
        "protection du climat",
        "stratégie climatique",
        "stratégie de changement climatique",
        "plan climat",
    ],
    "es": [
        "Plan de Acción Climática",
        "Plan climático",
        "Estrategia climática",
        "Estrategia de cambio climático",
        "Estrategia ambiental",
        "Estrategia resiliente",
        "Resiliente",
        "Sostenible",
        "Carbono neutral",
        "Vulnerabilidad climática",
        "Evaluación climática",
        "Hoja de ruta de acción climática",
        "Plan de emergencia climática",
        "Plan de mitigación climática",
        "Mitigación del cambio climático",
        "Plan de acción energética",
        "Plan de mitigación",
    ],
    "ru": [
        "защита климата",
        "климатическая стратегия",
        "стратегия изменения климата",
        "климатический план",
    ],
    "zh": ["气候保护", "气候战略", "气候变化战略", "气候计划"],
    "ja": ["気候保護", "気候戦略", "気候変動戦略", "気候計画"],
}

_GOOGLE_DOMAIN = {
    "en": "google.com",
    "de": "google.de",
    "fr": "google.fr",
    "es": "google.es",
    "ru": "google.ru",
    "zh": "google.com.hk",
    "ja": "google.co.jp",
}

_COUNTRY_TO_LANG = {
    "germany": "de",
    "austria": "de",
    "ger": "de",
    "aut": "de",
    "france": "fr",
    "belgium": "fr",
    "fra": "fr",
    "bel": "fr",
    "spain": "es",
    "mexico": "es",
    "colombia": "es",
    "argentina": "es",
    "peru": "es",
    "venezuela": "es",
    "chile": "es",
    "ecuador": "es",
    "bolivia": "es",
    "cuba": "es",
    "dominican republic": "es",
    "guatemala": "es",
    "honduras": "es",
    "el salvador": "es",
    "nicaragua": "es",
    "costa rica": "es",
    "panama": "es",
    "puerto rico": "es",
    "ury": "es",
    "pry": "es",
    "esp": "es",
    "mex": "es",
    "col": "es",
    "arg": "es",
    "per": "es",
    "ven": "es",
    "chl": "es",
    "ecu": "es",
    "bol": "es",
    "cub": "es",
    "dom": "es",
    "gtm": "es",
    "hnd": "es",
    "slv": "es",
    "nic": "es",
    "cri": "es",
    "pan": "es",
    "pri": "es",
    "russia": "ru",
    "rus": "ru",
    "china": "zh",
    "cn": "zh",
    "chn": "zh",
    "taiwan": "zh",
    "twn": "zh",
    "hong kong": "zh",
    "hongkong": "zh",
    "hkg": "zh",
    "macau": "zh",
    "macao": "zh",
    "mac": "zh",
    "japan": "ja",
    "jpn": "ja",
}
